import Head from "next/head";
import Image from "next/image";
import NavNext from "../components/NavNext";
import styles from "../styles/Home.module.css";
import { useEffect } from "react";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const defaultRandom = ["/seo", "crawler"];
  const random = Math.floor(Math.random() * defaultRandom.length);
  // useEffect(() => {
  //   setTimeout(() => {
  //     router.push(defaultRandom[random]);
  //   }, 20000);
  // }, []);
  return (
    <div>
      <Head>
        <title>Blue Ocean Global Technologies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NavNext />
      </main>
    </div>
  );
}
